import time

print("Welcome to the Premium and Mysterious Adventure of Mad Libs")
print ("Game Loading")
time.sleep(5)
print("            _____               .___             ")
print("           /     \  _____     __| _/ ____        ")
print("          /  \ /  \ \__  \   / __ |_/ __ \       ")
print("         /    Y    \ / __ \_/ /_/ |\  ___/       ")
print("         \____|__  /(____  /\____ | \___  >      ")
print("          \/      \/      \/     \/              ")

print("         __________                              ")
print("         \______   \ ___.__.                     ")
print("          |    |  _/<   |  |                     ")
print("          |    |   \ \___  |                     ")
print("          |______  / / ____|                     ")
print("                 \/  \/                          ")

print("           ________                                                ")
print("          /  _____/  __ __ _______   ____    ____    ____ _______  ")
print("         /   \  ___ |  |  ""\"\_  __ \ /    \  /  _ \  /  _ _  __ \ ")
print("         \    \_\  \|  |  / |  | \/|   |  \(  <_> )(  <_> )|  | \/ ")
print("          \______  /|____/  |__|   |___|  / \____/  \____/ |__|    ")
print("                 \/                     \/                         ")

place=input("Enter the name of a random place: ")
noun=input("Enter a random noun: ")
name=input("Enter the name of a random place: ")
name2=input("Enter a random noun: ")
adjective=input("Enter a random adjective: ")
color=input("Enter a random colour: ")
adjective2=input("Enter a random adjective: ")
plural_noun=input("Enter a plural noun" )
name3=input("Enter the name of a random creature: ")
animal=input("Enter the name of a random animal: ")
name_of_animal=input("Enter the name of the animal: ")
possession=input("Enter a random possession name: ")
location="Enter a random location: "
adjective3=input("Enter a random adjective: ")
noun2=input("Enter a random noun: ")
noun3=input("Enter a random noun: ")
plural_noun2=input("Enter a random plural noun: ")
adjective4=input("Enter a random adjective: ")
color2=input("Enter a random colour: ")
word=input("Enter a random word: ")
adjective5=input("Enter a random adjective: ")
noun4=input("Enter a random noun: ")
gemstone=input("Enter the name of a random gemstone: ")
sound=input("Enter a random sound: ")
adjective6=input("Enter a random adjective: ")
print("Thank you for entering all the info: ")
print("Generating a story,please wait! ")
time.sleep(4)
print("Almost Generated")
time.sleep(2)

print(str("Once upon a time, in a" + place +" far, far away, there lived a curious" + noun + "named" + name + ". One day, " + name + " stumbled upon an ancient" + adjective))
print(str("book hidden in the depths of the enchanted forest. The book was bound in" + color + " leather and emitted a faint glow."))
print(str("As " + name +"  opened the book, a magical portal appeared before them. Without hesitation, they stepped through, and suddenly, they"))
print(str("themselves in a " +  adjective2 +" realm filled with talking animals, floating islands, and " + plural_noun +" made of candy. The"))
print(str("first creature " + name3 +" encountered was a mischievous " + animal + " named " + name_of_animal + ". " + name + " had a penchant for playing pranks on"))
print(str("unsuspecting travelers. But " + name + " needed help—someone to retrieve the lost " + possession + " from the treacherous " + location + ". To"))
print(str("succeed, " + name +" had to solve three riddles posed by the wise " + adjective3 + " owl perched atop the " + noun2 + " tree. The first riddle"))
print(str("was: “What has keys but can’t open locks?” " + name3 + " scratched their head, pondering the answer. Was it a " + noun3 + "? Or perhaps "))
print(str("a " + plural_noun2 + " + ? After much contemplation, " + name2 +" blurted out, “A piano!” The owl nodded approvingly and revealed the next"))
print(str("challenge: " + name2 +" had to cross the " + adjective4 + " bridge guarded by a " + color2 + " dragon. The dragon demanded a secret password,"))
print(str("which turned out to be “" + word + ".” Finally, " + name2 + " reached the heart of the enchanted realm—a shimmering " + adjective5 + "waterfall"))
print(str("that concealed the lost " + noun4 + ". As they dipped their hand into the water, it transformed into a "))
print(str("sparkling " + gemstone + ". With the gemstone in hand, " + name2 + " returned to the real world, leaving behind the magical realm. But the"))
print(str(" adventure had changed them forever. Now, whenever they heard a " + sound + ", they could not help but smile, remembering the"))
print(str(" mysterious journey. And so, dear reader, if you ever find an old " + adjective6 +" book, don’t hesitate to open it. Who knows"))
print(str("what fantastical adventures await?"))
